services:
  mypantry-db:
    container_name: mypantry-db
    image: postgres
    environment:
      POSTGRES_DB: mypantry-db
      POSTGRES_USER: mypantry
      POSTGRES_PASSWORD: mypantry
      PGDATA: /data/postgres
    volumes:
      - mypantry-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - spring
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  kafka-broker:
    image: apache/kafka:3.7.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://kafka-broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_LOG_RETENTION_BYTES: 536870912  #536Mb
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_CLEANER_ENABLE: "true"
      KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - spring
    volumes:
      - kafka-data:/kafka-data
    restart: always

  redis-cache:
    container_name: redis-cache
    image: redis/redis-stack:7.4.0-v0
    volumes:
      - redis-cache:/local-data/:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - spring
    restart: always
    #Redis Insight exposed on port 8001

volumes:
  pgadmin:
  mypantry-db:
  kafka-data:
  redis-cache:
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge