spring:
  config:
    import: optional:file:.dev.env[.properties]

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mypantry-db
    username: mypantry
    password: mypantry
  jpa:
    hibernate:
      ddl-auto: validate
      defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    encoding: ISO-8859-1
    baselineOnMigrate: false  #Set to true when schema is not empty
    baselineVersion: 0
    create-schemas: true
    schemas: account
    default-schema: account
    locations: classpath:db/migration,classpath:db/migration-account

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 30000
      client-type: ${REDIS_CLIENT_TYPE:lettuce}
      repositories:
        enabled: false
  cache:
    type: redis

security-config:
  secret: ${SECURITY_SECRET}
  allowedOrigin: ${ALLOWED_ORIGINS}
  googleClientId: ${DV_GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}

cache-config:
  role_TTL: ${ROLE_TTL:5}
  members_TTL: ${MEMBERS_TTL:5}
  acl_TTL: ${ACL_TTL:5}

kafka-config:
  bootstrap-servers-config: localhost:29092
  purchase-create-topic: purchaseCreateTopic
  purchase-complete-topic: purchaseCompleteTopic
  product-topic: productTopic
  account-topic: accountTopic
  group: pantryGroup
  partitions: ${PARTITIONS:1}
  replicas: ${REPLICAS:1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    mappings:
      enabled: true